### ISSUE TITLE
The plugin does not load and is disabled on 1.19.3-1.19.4 paper server

### ISSUE THREAD

**Issue by Tarquitet** [aternosorg/motdgg-bukkit#3]
Well, I tried this plugin that really impressed me quite a bit with what it promises on the modrinth page until I put it on my server and the following error appears related to the version is not updated and yes, the plugin version is 1.3.0-bukkit.

Here is the log:
https://mclo.gs/oh0MYM5

**Comment by JulianVennen** [comment]
This should be resolved by v1.3.4
